# .github/workflows/sync.yml

name: Merge upstream branches
on:
  schedule:
     # Run once a day
    - cron:  '0 0 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'mrpopogod'
          git config --global user.email 'mrpopogod@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/Solaris-Skunk-Werks/solarisskunkwerks.git
          git fetch upstream

          # Neither forget the -b opt,
          # the develop ref is ambiguous at this stage
          git checkout -b develop origin/develop
          git merge --no-edit upstream/develop
          git push origin develop

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
